#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-io.github.aarron_lee.crunchyroll-linux}"

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/crunchyroll-linux/crunchyroll-linux "${FLAGS[@]}" "$@"