#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-io.github.aarron_lee.gkeep}"

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/gkeep/gkeep "${FLAGS[@]}" "$@"